- id: urlchecker
  name: urlchecker
  description: "urlchecker-python: test for and report broken links" 
  entry: urlchecker
  language: python
  language_version: python3
  minimum_pre_commit_version: 2.9.2
  #require_serial: true
  #types_or: [python, pyi]
